# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-fa6KroDnhGURHy3SlHbupYmlkud2bK
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv("sonar data.csv", header=None)

df.head()

df.shape

df.describe()

df[60].value_counts()

df.groupby(60).mean()

x = df.drop(columns=60, axis=1)
y = df[60]

print(x)
print(y)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.1, stratify=y, random_state=1)

print(x.shape, x_train.shape,x_test.shape)

model = LogisticRegression()
model.fit(x_train, y_train)

x_train_prediction = model.predict(x_train)
tr = accuracy_score(x_train_prediction, y_train)

print("Accuracy",tr)

x_test_prediction = model.predict(x_test)
tr1 = accuracy_score(x_test_prediction, y_test)

input_data = (0.0352,0.0116,0.0191,0.0469,0.0737,0.1185,0.1683,0.1541,0.1466,0.2912,0.2328,0.2237,0.2470,0.1560,0.3491,0.3308,0.2299,0.2203,0.2493,0.4128,0.3158,0.6191,0.5854,0.3395,0.2561,0.5599,0.8145,0.6941,0.6985,0.8660,0.5930,0.3664,0.6750,0.8697,0.7837,0.7552,0.5789,0.4713,0.1252,0.6087,0.7322,0.5977,0.3431,0.1803,0.2378,0.3424,0.2303,0.0689,0.0216,0.0469,0.0426,0.0346,0.0158,0.0154,0.0109,0.0048,0.0095,0.0015,0.0073,0.0067)

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
  print('The object is a Rock')
else:
  print('The object is a mine')
